default: &default
  adapter: postgresql
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>  
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: contacts-dev

test:
  <<: *default
  database: contacts-test

production:
  adapter: postgresql
  host: localhost
  username: user
  database: app-dev